// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw-7xuu4oJYkEQkbYuyveRKhFyvdLuzMA',
    appId: '1:207628892415:android:14c5421661944cb22974ca',
    messagingSenderId: '207628892415',
    projectId: 'atm-energy-7740b',
    databaseURL: 'https://atm-energy-7740b-default-rtdb.firebaseio.com',
    storageBucket: 'atm-energy-7740b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpo3mHqglIVHkscULSx_ZtqPuAKydmuk4',
    appId: '1:207628892415:ios:3e3a4be54af3e3df2974ca',
    messagingSenderId: '207628892415',
    projectId: 'atm-energy-7740b',
    databaseURL: 'https://atm-energy-7740b-default-rtdb.firebaseio.com',
    storageBucket: 'atm-energy-7740b.firebasestorage.app',
    iosBundleId: 'com.example.skyp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7PaGm7DdKPAnrKKDcOLXrcAYbuRwFSLA',
    appId: '1:207628892415:web:2ae989338bcebf972974ca',
    messagingSenderId: '207628892415',
    projectId: 'atm-energy-7740b',
    authDomain: 'atm-energy-7740b.firebaseapp.com',
    databaseURL: 'https://atm-energy-7740b-default-rtdb.firebaseio.com',
    storageBucket: 'atm-energy-7740b.firebasestorage.app',
    measurementId: 'G-WPT1FWZ4J1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpo3mHqglIVHkscULSx_ZtqPuAKydmuk4',
    appId: '1:207628892415:ios:3e3a4be54af3e3df2974ca',
    messagingSenderId: '207628892415',
    projectId: 'atm-energy-7740b',
    databaseURL: 'https://atm-energy-7740b-default-rtdb.firebaseio.com',
    storageBucket: 'atm-energy-7740b.firebasestorage.app',
    iosBundleId: 'com.example.skyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7PaGm7DdKPAnrKKDcOLXrcAYbuRwFSLA',
    appId: '1:207628892415:web:1ac76e5e90411bf12974ca',
    messagingSenderId: '207628892415',
    projectId: 'atm-energy-7740b',
    authDomain: 'atm-energy-7740b.firebaseapp.com',
    databaseURL: 'https://atm-energy-7740b-default-rtdb.firebaseio.com',
    storageBucket: 'atm-energy-7740b.firebasestorage.app',
    measurementId: 'G-6Q43GVKL91',
  );

}